### ISSUE TITLE
How to add config for proxy

### ISSUE THREAD

**Issue by Capotasto** [derek/node-yql#16]
HI, How can I add the proxy setting to the YQL request like below?

https://stackoverflow.com/a/6781592

 I tried this 
```
var query = new YQL(queryString);
query.setConfigs({
      host: proxyUrl,
      port: 8080
 });
```

But I don't  even know what kind option I can add this `config` so `host` or `post` is probably wrong.
This doesn't work at all.

**Comment by derek** [comment]
Hi @Capotasto, unfortunately this is an extremely old package (7 years) and I'm not even sure Yahoo is still maintaining YQL, so it is deprecated.  In the current state of this code, what you are hoping to do is not possible.  You probably achieve it by manually editing [yql.js](https://github.com/derek/node-yql/blob/master/yql.js#L195)'s `exec` method to include these lines in the `config` construction block.

        port: this.config.port,
        host: this.config.host,

**Comment by Capotasto** [comment]
@derek I see. Thank you. I am going to use `request` for this GET request.
